openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /tokens/list/:
    get:
      operationId: listget_token_lists
      description: "\u041F\u0440\u043E\u0441\u043C\u043E\u0442\u0440 \u0432\u0441\u0435\
        \u0445 \u0441\u043E\u0437\u0434\u0430\u043D\u043D\u044B\u0445 \u0442\u043E\
        \u043A\u0435\u043D\u043E\u0432.\n\u042D\u043D\u0434\u043F\u043E\u0438\u043D\
        \u0442:\n  * - tokens/list/"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - tokens
  /tokens/total_supply/:
    get:
      operationId: listget_total_supplys
      description: "\u0418\u043D\u0444\u043E\u0440\u043C\u0430\u0446\u0438\u044F \u043E\
        \ \u0442\u0435\u043A\u0443\u0449\u0435\u043C Total supply \u0442\u043E\u043A\
        \u0435\u043D\u0430.\n\u042D\u043D\u0434\u043F\u043E\u0438\u043D\u0442:\n \
        \ * - tokens/total_supply/"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - tokens
  /tokens/create/:
    post:
      operationId: createcreate_token
      description: "\u0421\u043E\u0437\u0434\u0430\u043D\u0438\u0435 \u0442\u043E\u043A\
        \u0435\u043D\u0430.\n\u042D\u043D\u0434\u043F\u043E\u0438\u043D\u0442:\n \
        \ * - tokens/create/\nRequest body:\n  {\n    \"media_url\": \"<\u0443\u0440\
        \u043B \u0441 \u043F\u0440\u043E\u0438\u0437\u0432\u043E\u043B\u044C\u043D\
        \u044B\u043C \u0438\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0435\
        \u043C>\",\n    \"owner\": \"<\u0430\u0434\u0440\u0435\u0441\u0441 \u0432\u043B\
        \u0430\u0434\u0435\u043B\u044C\u0446\u0430 \u0442\u043E\u043A\u0435\u043D\u0430\
        >\",\n  }"
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - tokens
