# Generated by Django 4.2.10 on 2024-02-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_hash', models.CharField(max_length=20, unique=True)),
                ('tx_hash', models.CharField(max_length=255)),
                ('media_url', models.URLField()),
                ('owner', models.CharField(max_length=255)),
            ],
        ),
    ]
